### ISSUE TITLE
Error connecting to device

### ISSUE THREAD

**Issue by TaylorHokanson** [sparkfun/Qwiic_Relay_Py#1]
I have an externally powered Sparkfun Quad Relay hooked up to a Raspberry Pi via Qwiic. When I run ```i2cdetect -y 1```, I get the following output:
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- UU -- -- -- -- 6d -- -- 
70: -- -- -- -- -- -- -- --                        
```
According to the demo code, that's the correct address for the Quad board. However, when I run the README sample code, I get the following error:
```
Error connecting to Device: 8, [Errno 121] Remote I/O error
The Qwiic Relay isn't connected to the system. Please check your connection
```
Interestingly, when I run code from the samples folder, I get an almost identical error but with a different device number:
```
Error connecting to Device: 18, [Errno 121] Remote I/O error
```
Any ideas about what I might be doing wrong?

**Comment by AndyEngland521** [comment]
Hi @TaylorHokanson aI'm guessing that you never switched the address for the library to use. This library is built for the Quad Solid State Relay, so if you're using the Regular ol' quad relay, you'll need to pass `QUAD_RELAY_DEFUALT_ADDR`  instead of `QUAD_SOLID_STATE_RELAY` into line 53 `myRelays = qwiic_relay.QwiicRelay(QUAD_SOLID_STATE_RELAY)` in example 1

**Comment by TaylorHokanson** [comment]
Aha! Good catch. Everything worked perfectly when I made the adjustment.
